- hosts:  localhost
  gather_facts:  false
  sudo:  no
  vars:
    git_name:  alisdair sullivan
    git_email:  alisdairsullivan@yahoo.ca
  tasks:
    - name:  update homebrew
      homebrew:  update_homebrew=yes
    - name:  install git
      homebrew:  name=git state=present
    - name:  configure git
      template:  src=templates/gitconfig.j2 dest=~/.gitconfig
    - name:  install erlang
      homebrew:  name=erlang state=present
    - name:  install elixir
      homebrew:  name=elixir state=present
    - name:  install todo.txt
      homebrew:  name='todo-txt' state=present
    - name:  ensure ~/todo exists
      file:  path=~/todo state=directory
    - name:  configure todo
      template:  src=templates/todo.config.j2 dest=~/todo/.config
    - name:  ~/.bash_profile
      template:  src=templates/bash_profile.j2 dest=~/.bash_profile